"""add_industry_experience_level

Revision ID: 6b6a06f1fcbe
Revises: 34ba12d78d2b
Create Date: 2026-06-26 20:07:04.413821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6a06f1fcbe'
down_revision: Union[str, Sequence[str], None] = '34ba12d78d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('experience_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'experience_level')
    op.drop_column('companies', 'industry')
    # ### end Alembic commands ###
